basePath: /
host: localhost:9090
info:
  contact:
    email: ooooooooooos@163.com
    name: silenceLamb
    url: http://www.swagger.io/support
  title: 快递代取 API
  version: 1.0.1
paths:
  /express/create:
    post:
      description: 这是一个新增订单接口
      parameters:
      - description: 快递单号
        in: formData
        name: code
        required: true
        type: string
      - description: 收货地址
        in: formData
        name: address
        required: true
        type: string
      - description: 收货日期
        in: formData
        name: receive_date
        required: true
        type: string
      - description: 订单费用
        in: formData
        name: price
        required: true
        type: string
      - description: 取件码
        in: formData
        name: receive_code
        required: true
        type: string
      - description: 创建人 id
        in: formData
        name: create_id
        required: true
        type: string
      - description: 创建人手机号
        in: formData
        name: create_phone
        required: true
        type: string
      - description: 商品图片
        in: formData
        name: good_img
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 新增订单
      tags:
      - 快递订单
  /express/finish:
    put:
      description: 完成订单接口 - 传入接单人 identity 为完成订单 传入创建人 identity 为收货
      parameters:
      - description: 订单 id
        in: query
        name: id
        required: true
        type: string
      - description: 用户唯一标识
        in: query
        name: identity
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 完成订单
      tags:
      - 快递订单
  /express/info:
    get:
      description: 这是一个订单详情接口
      parameters:
      - description: 订单 id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 订单详情
      tags:
      - 快递订单
  /express/list:
    get:
      description: 这是一个订单列表接口
      parameters:
      - description: 页码
        in: query
        name: page
        required: true
        type: string
      - description: 条数
        in: query
        name: size
        required: true
        type: string
      - description: 接单状态
        in: query
        name: status
        type: integer
      - description: 接单人
        in: query
        name: receiver_id
        type: string
      - description: 创建人
        in: query
        name: create_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 订单列表
      tags:
      - 快递订单
  /express/order:
    put:
      description: 这是一个接单接口
      parameters:
      - description: 订单 id
        in: query
        name: id
        required: true
        type: string
      - description: 接单人 id
        in: query
        name: receiver_id
        required: true
        type: string
      - description: 接单人手机号码
        in: query
        name: receiver_phone
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 接单
      tags:
      - 快递订单
  /upload:
    post:
      description: 上传文件接口
      parameters:
      - description: 上传的文件
        in: formData
        name: file
        required: true
        type: string
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 上传文件
      tags:
      - 上传文件
  /user/info:
    get:
      description: 用户详情接口
      parameters:
      - description: identity
        in: query
        name: identity
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 用户详情
      tags:
      - 用户
    put:
      description: 修改用户信息接口
      parameters:
      - description: 用户唯一标识
        in: query
        name: identity
        required: true
        type: string
      - description: 头像
        in: query
        name: avatar_url
        type: string
      - description: 电子邮箱
        in: query
        name: mail
        type: string
      - description: 昵称
        in: query
        name: name
        type: string
      - description: 手机号码
        in: query
        name: phone
        type: string
      - description: 账户
        in: query
        name: user_name
        type: string
      - description: 密码
        in: query
        name: password
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 修改用户信息
      tags:
      - 用户
  /user/login:
    post:
      description: 用户登录接口
      parameters:
      - description: code
        in: formData
        name: code
        required: true
        type: string
      - description: 名字
        in: formData
        name: name
        required: true
        type: string
      - description: 头像
        in: formData
        name: avatarUrl
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 用户登录
      tags:
      - 用户
swagger: "2.0"
